### ISSUE TITLE
pre-commit error

### ISSUE THREAD

**Issue by yingxingcheng** [reproducible-reporting/templates#1]
I got some errors when I run `pre-commit`:

```log
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/lovesegfault/beautysh.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/yxcheng/.cache/pre-commit/repov9kz1w3m/py_env-python3.11/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /Users/yxcheng/.cache/pre-commit/repov9kz1w3m
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [26 lines of output]
          /private/var/folders/29/wzvrkvk14dv3q6hyljdp_tmm0000gn/T/pip-build-env-twr9pg90/overlay/lib/python3.11/site-packages/setuptools_scm/git.py:135: UserWarning: "/Users/yxcheng/.cache/pre-commit/repov9kz1w3m" is shallow and may cause errors
            warnings.warn(f'"{wd.path}" is shallow and may cause errors')
          Traceback (most recent call last):
            File "/Users/yxcheng/.cache/pre-commit/repov9kz1w3m/py_env-python3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/Users/yxcheng/.cache/pre-commit/repov9kz1w3m/py_env-python3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/yxcheng/.cache/pre-commit/repov9kz1w3m/py_env-python3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
              whl_basename = backend.build_wheel(metadata_directory, config_settings)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/29/wzvrkvk14dv3q6hyljdp_tmm0000gn/T/pip-build-env-twr9pg90/overlay/lib/python3.11/site-packages/hatchling/build.py", line 56, in build_wheel
              return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/29/wzvrkvk14dv3q6hyljdp_tmm0000gn/T/pip-build-env-twr9pg90/overlay/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 158, in build
              artifact = version_api[version](directory, **build_data)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/29/wzvrkvk14dv3q6hyljdp_tmm0000gn/T/pip-build-env-twr9pg90/overlay/lib/python3.11/site-packages/hatchling/builders/wheel.py", line 371, in build_standard
              record = archive.add_file(included_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/29/wzvrkvk14dv3q6hyljdp_tmm0000gn/T/pip-build-env-twr9pg90/overlay/lib/python3.11/site-packages/hatchling/builders/wheel.py", line 89, in add_file
              zip_info = zipfile.ZipInfo(relative_path, cast(TIME_TUPLE, self.time_tuple))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/yxcheng/yingxing_paper/env/lib/python3.11/zipfile.py", line 388, in __init__
              raise ValueError('ZIP does not support timestamps before 1980')
          ValueError: ZIP does not support timestamps before 1980
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
Check the log at /Users/yxcheng/.cache/pre-commit/pre-commit.log
```

**Comment by yingxingcheng** [comment]
ps. add `pre-commit` to default `requirements.txt`? I installed it manually.

**Comment by lcdumort** [comment]
I can reproduce this error on my (Linux) system
